language: rust
sudo: true
os: linux
dist: focal
arch:
    - amd64
rust:
  - stable
  - beta
  - nightly
jobs:
  fast_finish: true
compiler:
  - gcc
  - musl-gcc
install:
  - rustup target add x86_64-unknown-linux-musl
  - sudo apt-get install -y musl-tools musl musl-dev
  - cargo test
  - cargo build --release --target x86_64-unknown-linux-musl
  - cp target/release/closeany target/release/closeany-linux-amd64

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "target/release/closeany-linux-amd64"
  skip_cleanup: true
  on:
    tags: true
